/*
 * app.h - single-window application handle, event loop and input.
 *
 * Usage
 * -----
 *   rc_app_callbacks cb = {0};
 *   cb.ctx        = &state;
 *   cb.on_key_down = my_key_down;
 *   cb.on_render   = my_render;
 *
 *   rc_app_desc desc = {0};
 *   desc.title     = RC_STR("My App");
 *   desc.width     = 1280;
 *   desc.height    = 720;
 *   desc.resizable = true;
 *   desc.callbacks = cb;
 *
 *   rc_app *app = rc_app_make(&desc);
 *   while (rc_app_is_running(app)) {
 *       rc_app_poll(app);
 *       rc_app_request_update(app);
 *       rc_app_request_render(app);
 *       rc_app_swap(app);
 *   }
 *   rc_app_destroy(app);
 *
 * Update and render callbacks
 * ---------------------------
 * Call rc_app_request_update / rc_app_request_render from the main loop
 * rather than invoking on_update / on_render directly.  This allows the
 * backend to also trigger on_render from the OS window-refresh callback,
 * ensuring rendering occurs during modal resize without extra user code.
 */

#ifndef RC_APP_H_
#define RC_APP_H_

#include <stdbool.h>
#include <stdint.h>
#include "richc/str.h"
#include "richc/math/vec2i.h"
#include "richc_app/keys.h"

/* ---- callbacks ---- */

/*
 * All callbacks are optional — leave NULL to ignore that event.
 * ctx is forwarded as the first argument of every callback.
 */
typedef struct {
    void *ctx;

    /* Keyboard — physical key pressed/released (use scancode for layout-
     * independent input such as game controls).  REPEAT events are filtered
     * out; use on_key_char for text input at the OS auto-repeat cadence. */
    void (*on_key_down)   (void *ctx, rc_scancode scancode, rc_mod mods);
    void (*on_key_up)     (void *ctx, rc_scancode scancode, rc_mod mods);

    /* Text input — Unicode codepoint generated by a key press or auto-repeat.
     * Use this for typing rather than on_key_down. */
    void (*on_key_char)   (void *ctx, uint32_t codepoint, rc_mod mods);

    /* Mouse buttons */
    void (*on_mouse_down) (void *ctx, rc_mouse_button button, rc_mod mods);
    void (*on_mouse_up)   (void *ctx, rc_mouse_button button, rc_mod mods);

    /* Cursor entered or left the window's client area */
    void (*on_mouse_enter)(void *ctx);
    void (*on_mouse_leave)(void *ctx);

    /* Cursor moved — pos is in window coordinates, pixels, origin top-left */
    void (*on_mouse_move) (void *ctx, rc_vec2i pos);

    /* Scroll wheel or trackpad — delta in scroll-click units */
    void (*on_mouse_wheel)(void *ctx, rc_vec2i delta);

    /* Framebuffer resized — size is in physical pixels */
    void (*on_resize)     (void *ctx, rc_vec2i size);

    /* Window state changes */
    void (*on_focus_gained)(void *ctx);
    void (*on_focus_lost)  (void *ctx);
    void (*on_minimize)    (void *ctx);
    void (*on_maximize)    (void *ctx);

    /* Frame callbacks — call via rc_app_request_update/render, not directly */
    void (*on_update)     (void *ctx, double dt);
    void (*on_render)     (void *ctx);
} rc_app_callbacks;

/* ---- descriptor ---- */

typedef struct {
    rc_str   title;
    int32_t  width;
    int32_t  height;
    bool     resizable;

    /* Graphics hints */
    bool     srgb;
    int32_t  depth_bits;    /* 0 = no depth buffer */
    int32_t  msaa_samples;  /* 0 or 1 = no MSAA    */

    rc_app_callbacks callbacks;
} rc_app_desc;

/* ---- API ---- */

void     rc_app_init           (const rc_app_desc *desc);
void     rc_app_destroy        (void);
void     rc_app_poll           (void);
bool     rc_app_is_running     (void);
rc_vec2i rc_app_size           (void);

/* Invoke on_update(ctx, dt) with the time elapsed since the last call. */
void     rc_app_request_update (void);

/* Set the viewport to the full framebuffer, invoke on_render(ctx), then
 * swap buffers.  Also called internally on OS window-refresh (e.g. during
 * modal resize) so rendering stays live without extra user code. */
void     rc_app_request_render (void);

#endif /* RC_APP_H_ */
