/*
 * events.h - event structs passed to rc_app callbacks.
 *
 * All events are passed by value to callbacks.  Fields not relevant to a
 * particular event type are left at their zero value.
 */

#ifndef RC_APP_EVENTS_H_
#define RC_APP_EVENTS_H_

#include <stdint.h>
#include "richc_app/keys.h"

/* A key was pressed, released, or repeated. */
typedef struct {
    rc_key    key;
    rc_action action;
    rc_mod    mods;
} rc_key_event;

/* A mouse button was pressed or released. */
typedef struct {
    rc_mouse_button button;
    rc_action       action;
    rc_mod          mods;
} rc_mouse_event;

/* The cursor moved.  Coordinates are in screen pixels, origin top-left. */
typedef struct {
    double x;
    double y;
} rc_cursor_event;

/* The scroll wheel or trackpad scrolled. */
typedef struct {
    double dx;
    double dy;
} rc_scroll_event;

/* The framebuffer was resized (may differ from window size on HiDPI). */
typedef struct {
    int32_t width;
    int32_t height;
} rc_resize_event;

/* A Unicode codepoint was generated by a key press. */
typedef struct {
    uint32_t codepoint;
} rc_char_event;

#endif /* RC_APP_EVENTS_H_ */
